### ISSUE TITLE
Install errors on Deno 1.9, 1.10 and 1.11

### ISSUE THREAD

**Issue by shah** [cdaringe/markdown_player#2]
Hi @cdaringe - this seems like a great library and I'm trying to use it to run SQL through psql and generate dynamic Markdown output from a PostgreSQL database. Unfortunately, I did not get very far when trying it :-)

### Using Deno 1.9.2 and 1.10.3 in Ubuntu 20.04 on WSL2 on Windows 10:

```bash
❯ deno install --unstable -f -A -n markdown-player "https://deno.land/x/markdown_player@v1.2.1/src/bin.ts"
Check https://deno.land/x/markdown_player@v1.2.1/src/bin.ts
error: TS18022 [ERROR]: A method cannot be named with a private identifier.
  #tryGrowByReslice(n: number) {
  ~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.98.0/io/buffer.ts:85:3

TS18022 [ERROR]: A method cannot be named with a private identifier.
  #reslice(len: number) {
  ~~~~~~~~
    at https://deno.land/std@0.98.0/io/buffer.ts:94:3

TS18022 [ERROR]: A method cannot be named with a private identifier.
  #grow(n: number) {
  ~~~~~
    at https://deno.land/std@0.98.0/io/buffer.ts:141:3

Found 3 errors.
```

### Using Deno 1.11.0 in Ubuntu 20.04 on WSL2 on Windows 10:

```bash
❯ deno install --unstable -f -A -n markdown_player "https://deno.land/x/markdown_player@v1.2.1/src/bin.ts"
Check https://deno.land/x/markdown_player@v1.2.1/src/bin.ts
# hangs and never returns to CLI, does not install markdown_player 
```

The above version just "hangs" for many minutes and I have to Ctrl+C out.

Any thoughts on what I do?

**Comment by cdaringe** [comment]
Bummer, looks like the standard library version of buffer perhaps is incompatible with your system and version of deno. Problems like this are quite common since the early days of deno, while all of the APIs began to stabilize. The solution is probably to simply upgrade dependencies here: https://github.com/cdaringe/markdown_player/blob/main/src/3p.ts

Your stack trace doesn't show the full trace, which if possible could be helpful to find the actual culprit module, as I do not consume buffer directly (IIRC? I might, I'm on my phone, so I'm not 100% sure at the moment).

That would address the first issue. The second issue is unlikely to do with this package at all, and likely some other tooling issue of which I cannot assist with.

**Comment by shah** [comment]
Thanks for the quick reply @cdaringe - could you let me know OS, version of Deno, etc. you've tested with? I'll try to match to accommodate while debugging.

**Comment by cdaringe** [comment]
Ya, you can see it all in .github/ folder, where CI is configured!

Probably the easiest solution is to fork, and try rolling those versions
forward in 3p.ts! I assume there is some newer std version which is more
windows friendly. I can otherwise try later in the week! However, I do not
have handy windows access

**Comment by shah** [comment]
Thanks @cdaringe I'm running a `Ubuntu 20.04` VM _on Windows_ rather than Windows directly. I suspect it has more to do with newer Deno stdlib version. I'll try it out but would be great if you can as well.

**Comment by shah** [comment]
Even with the same version that you're using (Deno 1.8.2) on Ubuntu 20.04 I appear to be getting the same error:

```bash
❯ deno --version
deno 1.8.2 (release, x86_64-unknown-linux-gnu)
v8 9.0.257.3
typescript 4.2.2

❯ deno install --unstable -f -A -n markdown_player "https://deno.land/x/markdown_player@v1.2.1/src/bin.ts"
Check https://deno.land/x/markdown_player@v1.2.1/src/bin.ts
error: TS18022 [ERROR]: A method cannot be named with a private identifier.
  #tryGrowByReslice(n: number) {
  ~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.98.0/io/buffer.ts:85:3

TS18022 [ERROR]: A method cannot be named with a private identifier.
  #reslice(len: number) {
  ~~~~~~~~
    at https://deno.land/std@0.98.0/io/buffer.ts:94:3

TS18022 [ERROR]: A method cannot be named with a private identifier.
  #grow(n: number) {
  ~~~~~
    at https://deno.land/std@0.98.0/io/buffer.ts:141:3

Found 3 errors.
```

**Comment by cdaringe** [comment]
Hey @shah, I managed to:

- update std to std@0.99
- rolled deno forward to 1.11.1

```
❯ deno --version
deno 1.11.1 (release, x86_64-apple-darwin)
v8 9.1.269.35
typescript 4.3.2
```

install & tests are all passing in CI: https://github.com/cdaringe/markdown_player/runs/2867843707.

Automated release cut version `1.2.3`.

Lemme know if that addresses it!

**Comment by shah** [comment]
Thanks @cdaringe I'll check it out again!

**Comment by shah** [comment]
Great work @cdaringe the tests pass on my machine WSL2 Ubuntu 18.04 box with Deno 1.11.1.
